<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Cdr extends Model
{
    //protected $table = 'cdr';
    protected $guarded = ['id'];

    public function getTable()
    {
        return 'cdr_'.date('Ym');
        //return parent::getTable(); // TODO: Change the autogenerated stub
    }

}
